<?php
   add_filter( 'elementor/icons_manager/additional_tabs', 'welowe_custom_icons_filters' , 9999999, 1 );
   function welowe_custom_icons_filters( $tabs = array() ) {
      $newicons = [
         'wicon-web',
         'wicon-chat',
         'wicon-speech-bubble',
         'wicon-plus1',
         'wicon-minus',
         'wicon-search',
         'wicon-call',
         'wicon-location1',
         'wicon-tshirt',
         'wicon-video-camera',
         'wicon-project-management',
         'wicon-salad',
         'wicon-reading-book',
         'wicon-crowdfunding-5',
         'wicon-badge',
         'wicon-support1',
         'wicon-pin-2',
         'wicon-phone-call1',
         'wicon-account',
         'wicon-cyborg',
         'wicon-reading-book-1',
         'wicon-success',
         'wicon-budget',
         'wicon-mission-2',
         'wicon-mission-3',
         'wicon-relationship',
         'wicon-trusted',
         'wicon-cost-saving',
         'wicon-recommend',
         'wicon-group',
         'wicon-campaign',
         'wicon-confirmation',
         'wicon-video-camera-1',
         'wicon-lamp',
         'wicon-mountain',
         'wicon-rocket',
         'wicon-crowdfunding-6',
         'wicon-invention-1',
         'wicon-email',
         'wicon-pin',
         'wicon-networking',
         'wicon-photograph',
         'wicon-stethoscope',
         'wicon-skincare',
         'wicon-computer',
         'wicon-checkmark',
         'wicon-mission',
         'wicon-team',
         'wicon-increment',
         'wicon-right-arrow',
         'wicon-left-arrow',
         'wicon-handshake',
         'wicon-shopping-cart-1',
         'wicon-shopping-cart',
         'wicon-camera',
         'wicon-video-camera-2',
         'wicon-camera-1',
         'wicon-donate',
         'wicon-charity',
         'wicon-share',
         'wicon-drops',
         'wicon-kindness',
         'wicon-donate-1',
         'wicon-health',
         'wicon-non-profit-organization',
         'wicon-right',
         'wicon-calendar',
         'wicon-location',
         'wicon-maps-and-flags',
         'wicon-play-button-arrowhead',
         'wicon-check-mark',
         'wicon-check',
         'wicon-service',
         'wicon-approved',
         'wicon-network',
         'wicon-medal',
         'wicon-donation',
         'wicon-phone-2',
         'wicon-star',
         'wicon-fruit',
         'wicon-medicine',
         'wicon-education',
         'wicon-house',
         'wicon-quote',
         'wicon-charity-2',
         'wicon-volunteer',
         'wicon-debit-card',
         'wicon-solidarity',
         'wicon-nature',
         'wicon-agronomy',
         'wicon-wind-energy',
         'wicon-recycling',
         'wicon-container',
         'wicon-ocean',
         'wicon-forest',
         'wicon-polar-bear',
         'wicon-igloo',
         'wicon-planet-earth',
         'wicon-environment',
         'wicon-ecological',
         'wicon-forest-1',
         'wicon-quotes',
         'wicon-quote-1',
         'wicon-question',
         'wicon-solidarity-1',
         'wicon-help',
         'wicon-map',
         'wicon-envelope',
         'wicon-phone-call',
         'wicon-chat-2',
         'wicon-donation-1',
         'wicon-adoption',
         'wicon-support',
         'wicon-message',
         'wicon-right-arrow-2',
         'wicon-exploration',
         'wicon-college',
         'wicon-charity-3',
         'wicon-checked',
         'wicon-message-1',
         'wicon-generous',
         'wicon-comment',
         'wicon-delete',
         'wicon-maternity',
         'wicon-quote-2',
         'wicon-clipboard',
         'wicon-cheque',
         'wicon-coin',
         'wicon-water',
         'wicon-heart',
         'wicon-heart-1',
         'wicon-fast-food',
         'wicon-phone',
         'wicon-handshake-2',
         'wicon-address',
         'wicon-left-arrow-2',
         'wicon-charity-4',
         'wicon-focus',
         'wicon-magnifying-glass',
         'wicon-donation-2',
         'wicon-check-2',
         'wicon-dove',
         'wicon-graduation',
         'wicon-health-check',
         'wicon-star-2',
         'wicon-email-3'
      ];

      $icons['gva_custom_icon'] = array(
           'name'          => 'welowe-icons-theme',
           'label'         => esc_html__( 'Icons Theme', 'welowe-themer' ),
           'labelIcon'     => 'fas fa-user',
           'prefix'        => '',
           'displayPrefix' => '',
           'icons'         => $newicons,
           'url'          => GAVIAS_WELOWE_PLUGIN_URL . 'assets/icons/style.css',
           'ver'           => '1.0',
       );

      return array_merge( $tabs, $icons );
   }

   add_action( 'wp_print_footer_scripts', 'welowe_insert_icons_footer_css'  );
   function welowe_insert_icons_footer_css() {
      echo '<link rel="stylesheet" type="text/css" href="' . GAVIAS_WELOWE_PLUGIN_URL . 'assets/icons/style.css">';
   }
