# name: Build and Deploy to Azure Web App

#on:
#  push:
#    branches:
#      - main  # Deploy when pushing to main branch

#jobs:
 # build-and-deploy:
  #  runs-on: ubuntu-latest

  #  steps:
      # Step 1: Checkout code
    #  - name: Checkout repository
    #    uses: actions/checkout@v3

      # Step 2: Set up Node.js (adjust version as needed)
    #  - name: Set up Node.js
    #    uses: actions/setup-node@v3
      #  with:
     #     node-version: '18.x'

      # Step 3: Install dependencies
    #  - name: Install dependencies
      #  run: npm install

      # Step 4: Build project
    #  - name: Build project
       # run: npm run build

      # Step 5: Deploy to Azure Web App
     # - name: Deploy to Azure Web App
       # uses: azure/webapps-deploy@v2
       # with:
        #  app-name: smileofhope
        #  slot-name: production
         # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #  package: .

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy WordPress app to Azure Web App - smileofhope-production
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: wordpress-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC65104514E6449A90FA8B6AAB1F1E95 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C44554CE0A6A4D22B7A1C21FBFF498DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB792355ADE7420DA689B2AD2A85FB6F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'smileofhope-production'
          slot-name: 'Production'
          package: .
          
